version: 1.2

workflows:
   -  name: Secphase
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/secphase.wdl
   -  name: CorrectBam
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/correct_bam.wdl
   -  name: GetSecphasedReadIds
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/get_secphased_read_ids.wdl
   -  name: WhatshapHaplotag 
      subclass: WDL
      primaryDescriptorPath: /wdls/workflows/whatshap_haplotag.wdl
